/*
 * Encog(tm) Core v3.0 - Java Version
 * http://www.heatonresearch.com/encog/
 * http://code.google.com/p/encog-java/
 
 * Copyright 2008-2011 Heaton Research, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *   
 * For more information on Heaton Research copyrights, licenses 
 * and trademarks visit:
 * http://www.heatonresearch.com/copyright
 */
// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 5/5/11 3:33 PM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using Encog.ML.Train;
using Encog.Util;

namespace Encog.App.Analyst
{
    /// <summary>
    /// A console implementation of the Encog Analyst listener. Will report all
    /// progress to the console.
    /// </summary>
    ///
    public class ConsoleAnalystListener : AnalystListener
    {
        /// <summary>
        /// Stopwatch to time process.
        /// </summary>
        ///
        private readonly Stopwatch stopwatch;

        /// <summary>
        /// True if the current command should be canceled.
        /// </summary>
        ///
        private bool cancelCommand;

        /// <summary>
        /// The current task.
        /// </summary>
        ///
        private String currentTask;

        /// <summary>
        /// True if shutdown has been requested.
        /// </summary>
        ///
        private bool shutdownRequested;

        public ConsoleAnalystListener()
        {
            currentTask = "";
            stopwatch = new Stopwatch();
        }

        #region AnalystListener Members

        /// <summary>
        /// 
        /// </summary>
        ///
        public void Report(int total, int current,
                           String message)
        {
            if (total == 0)
            {
                Console.Out.WriteLine(current + " : " + message);
            }
            else
            {
                Console.Out.WriteLine(current + "/" + total + " : " + message);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        ///
        public void ReportCommandBegin(int total, int current,
                                       String name)
        {
            Console.Out.WriteLine();
            if (total == 0)
            {
                Console.Out.WriteLine("Beginning Task#" + current + " : " + name);
            }
            else
            {
                Console.Out.WriteLine("Beginning Task#" + current + "/" + total
                                      + " : " + name);
            }
            currentTask = name;
            stopwatch.Start();
        }

        /// <summary>
        /// 
        /// </summary>
        ///
        public void ReportCommandEnd(bool cancel)
        {
            String cancelStr = "";
            cancelCommand = false;
            stopwatch.Stop();

            if (cancel)
            {
                cancelStr = "canceled";
            }
            else
            {
                cancelStr = "completed";
            }

            Console.Out.WriteLine("Task "
                                  + currentTask
                                  + " "
                                  + cancelStr
                                  + ", task elapsed time "
                                  + Format.FormatTimeSpan((int) (stopwatch.ElapsedMilliseconds/Format.MILI_IN_SEC)));
        }

        /// <summary>
        /// 
        /// </summary>
        ///
        public void ReportTraining(MLTrain train)
        {
            Console.Out.WriteLine("Iteration #"
                                  + Format.FormatInteger(train.IterationNumber)
                                  + " Error:"
                                  + Format.FormatPercent(train.Error)
                                  + " elapsed time = "
                                  + Format.FormatTimeSpan((int) (stopwatch.ElapsedMilliseconds/Format.MILI_IN_SEC)));
        }

        /// <summary>
        /// 
        /// </summary>
        ///
        public virtual void ReportTrainingBegin()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        ///
        public virtual void ReportTrainingEnd()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        ///
        [MethodImpl(MethodImplOptions.Synchronized)]
        public void RequestCancelCommand()
        {
            cancelCommand = true;
        }

        /// <summary>
        /// 
        /// </summary>
        ///
        [MethodImpl(MethodImplOptions.Synchronized)]
        public void RequestShutdown()
        {
            shutdownRequested = true;
        }

        /// <summary>
        /// 
        /// </summary>
        ///
        [MethodImpl(MethodImplOptions.Synchronized)]
        public bool ShouldShutDown()
        {
            return shutdownRequested;
        }

        /// <summary>
        /// 
        /// </summary>
        ///
        [MethodImpl(MethodImplOptions.Synchronized)]
        public bool ShouldStopCommand()
        {
            return cancelCommand;
        }

        #endregion
    }
}