/*
 * Encog(tm) Core v3.0 - Java Version
 * http://www.heatonresearch.com/encog/
 * http://code.google.com/p/encog-java/
 
 * Copyright 2008-2011 Heaton Research, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *   
 * For more information on Heaton Research copyrights, licenses 
 * and trademarks visit:
 * http://www.heatonresearch.com/copyright
 */
// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 5/5/11 3:33 PM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;

namespace Encog.App.Analyst.CSV.Basic
{
    /// <summary>
    /// A column that is based off of a column in a CSV file.
    /// </summary>
    ///
    public class FileData : BaseCachedColumn
    {
        /// <summary>
        /// The date.
        /// </summary>
        ///
        public const String DATE = "date";

        /// <summary>
        /// The time.
        /// </summary>
        ///
        public const String TIME = "time";

        /// <summary>
        /// The high value.
        /// </summary>
        ///
        public const String HIGH = "high";

        /// <summary>
        /// The low value.
        /// </summary>
        ///
        public const String LOW = "low";

        /// <summary>
        /// The open value.
        /// </summary>
        ///
        public const String OPEN = "open";

        /// <summary>
        /// The close value.
        /// </summary>
        ///
        public const String CLOSE = "close";

        /// <summary>
        /// The volume.
        /// </summary>
        ///
        public const String VOLUME = "volume";

        /// <summary>
        /// Construct the object.
        /// </summary>
        ///
        /// <param name="theName">The name of the object.</param>
        /// <param name="theIndex">The index of the field.</param>
        /// <param name="theInput">Is this field for input?</param>
        /// <param name="theOutput">Is this field for output?</param>
        public FileData(String theName, int theIndex,
                        bool theInput, bool theOutput) : base(theName, theInput, theOutput)
        {
            Output = theOutput;
            Index = theIndex;
        }

        /// <summary>
        /// Set the index of this field.
        /// </summary>
        ///
        /// <value>The index of this field.</value>
        public int Index { /// <returns>The index of this field.</returns>
            get; /// <summary>
            /// Set the index of this field.
            /// </summary>
            ///
            /// <param name="theIndex">The index of this field.</param>
            set; }
    }
}