/*
 * Encog(tm) Core v3.0 - Java Version
 * http://www.heatonresearch.com/encog/
 * http://code.google.com/p/encog-java/
 
 * Copyright 2008-2011 Heaton Research, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *   
 * For more information on Heaton Research copyrights, licenses 
 * and trademarks visit:
 * http://www.heatonresearch.com/copyright
 */
// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 5/5/11 3:32 PM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;
using Encog.Util.CSV;

namespace Encog.App.Analyst.CSV.Basic
{
    /// <summary>
    /// A row of a CSV file loaded to memory. This class is used internally by many
    /// of the Encog quant classes.
    /// </summary>
    ///
    public class LoadedRow
    {
        /// <summary>
        /// The row data.
        /// </summary>
        ///
        private readonly String[] data;

        /// <summary>
        /// Load a row from the specified CSV file.
        /// </summary>
        ///
        /// <param name="csv">The CSV file to use.</param>
        public LoadedRow(ReadCSV csv) : this(csv, 0)
        {
        }

        /// <summary>
        /// Construct a loaded row.
        /// </summary>
        ///
        /// <param name="csv">The CSV file to use.</param>
        /// <param name="extra">The number of extra columns to add.</param>
        public LoadedRow(ReadCSV csv, int extra)
        {
            int count = csv.GetCount();
            data = new String[count + extra];
            for (int i = 0; i < count; i++)
            {
                data[i] = csv.Get(i);
            }
        }


        /// <value>The row data.</value>
        public String[] Data
        {
            /// <returns>The row data.</returns>
            get { return data; }
        }
    }
}