// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 5/5/11 3:32 PM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 namespace Encog.ML.Genetic.Population {
	
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	public class Population_Constants {
	
		/// <summary>
		/// Property tag for the next gene id.
		/// </summary>
		///
		public const String PROPERTY_NEXT_GENE_ID = "nextGeneID";
		/// <summary>
		/// Property tag for the next genome id.
		/// </summary>
		///
		public const String PROPERTY_NEXT_GENOME_ID = "nextGenomeID";
		/// <summary>
		/// Property tag for the next innovation id.
		/// </summary>
		///
		public const String PROPERTY_NEXT_INNOVATION_ID = "nextInnovationID";
		/// <summary>
		/// Property tag for the next species id.
		/// </summary>
		///
		public const String PROPERTY_NEXT_SPECIES_ID = "nextSpeciesID";
		/// <summary>
		/// Property tag for the old age penalty.
		/// </summary>
		///
		public const String PROPERTY_OLD_AGE_PENALTY = "oldAgePenalty";
		/// <summary>
		/// Property tag for the old age threshold.
		/// </summary>
		///
		public const String PROPERTY_OLD_AGE_THRESHOLD = "oldAgeThreshold";
		/// <summary>
		/// Property tag for the population size.
		/// </summary>
		///
		public const String PROPERTY_POPULATION_SIZE = "populationSize";
		/// <summary>
		/// Property tag for the survival rate.
		/// </summary>
		///
		public const String PROPERTY_SURVIVAL_RATE = "survivalRate";
		/// <summary>
		/// Property tag for the young age bonus.
		/// </summary>
		///
		public const String PROPERTY_YOUNG_AGE_BONUS = "youngAgeBonus";
		/// <summary>
		/// Property tag for the young age threshold.
		/// </summary>
		///
		public const String PROPERTY_YOUNG_AGE_THRESHOLD = "youngAgeThreshold";
		/// <summary>
		/// Property tag for the genomes collection.
		/// </summary>
		///
		public const String PROPERTY_GENOMES = "genomes";
		/// <summary>
		/// Property tag for the innovations collection.
		/// </summary>
		///
		public const String PROPERTY_INNOVATIONS = "innovations";
		/// <summary>
		/// Property tag for the species collection.
		/// </summary>
		///
		public const String PROPERTY_SPECIES = "species"; 
	}
}
