/*
 * Encog(tm) Core v2.5 - Java Version
 * http://www.heatonresearch.com/encog/
 * http://code.google.com/p/encog-java/
 
 * Copyright 2008-2010 Heaton Research, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *   
 * For more information on Heaton Research copyrights, licenses 
 * and trademarks visit:
 * http://www.heatonresearch.com/copyright
 */

/// ---------------------------------------------------------------------------------------------------
///  This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
///  Version 1.0.0                                                                                      
/// ---------------------------------------------------------------------------------------------------
 namespace Org.Encog.Engine.Network.Rbf {
	
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Runtime.CompilerServices;
	
	/// <summary>
	/// A multi-dimension RBF.
	/// </summary>
	///
	public interface RadialBasisFunction {
		/// <summary>
		/// Calculate the RBF result for the specified value.
		/// </summary>
		///
		/// <param name="x"/>The value to be passed into the RBF.</param>
		/// <returns>The RBF value.</returns>
		double Calculate(double[] x);
	
		/// <summary>
		/// Get the center of this RBD.
		/// </summary>
		///
		/// <param name="dimension"/>The dimension to get the center for.</param>
		/// <returns>The center of the RBF.</returns>
		double GetCenter(int dimension);
	
		/// <summary>
		/// Set the peak.
		/// </summary>
		///
		/// <param name="peak"/>The peak.</param>
		double Peak {
		/// <summary>
		/// Get the center of this RBD.
		/// </summary>
		///
		/// <returns>The center of the RBF.</returns>
		  get;
		/// <summary>
		/// Set the peak.
		/// </summary>
		///
		/// <param name="peak"/>The peak.</param>
		  set;
		}
		
	
		/// <summary>
		/// Set the width.
		/// </summary>
		///
		/// <param name="radius"/>The width.</param>
		double Width {
		
		/// <returns>The width of the RBF.</returns>
		  get;
		/// <summary>
		/// Set the width.
		/// </summary>
		///
		/// <param name="radius"/>The width.</param>
		  set;
		}
		
	
		
		/// <returns>The dimensions in this RBF.</returns>
		int Dimensions {
		
		/// <returns>The dimensions in this RBF.</returns>
		  get;
		}
		
	
		/// <summary>
		/// Set the centers.
		/// </summary>
		///
		/// <param name="center"/>The centers.</param>
		double[] Centers {
		
		/// <returns>Get the centers.</returns>
		  get;
		/// <summary>
		/// Set the centers.
		/// </summary>
		///
		/// <param name="center"/>The centers.</param>
		  set;
		}
		
	}
}
