/*
 * Encog(tm) Core v3.0 - Java Version
 * http://www.heatonresearch.com/encog/
 * http://code.google.com/p/encog-java/
 
 * Copyright 2008-2011 Heaton Research, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *   
 * For more information on Heaton Research copyrights, licenses 
 * and trademarks visit:
 * http://www.heatonresearch.com/copyright
 */
// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 5/5/11 3:33 PM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;
using System.Text;

namespace Encog.Util
{
    public class HTMLReport
    {
        private readonly StringBuilder text;

        public HTMLReport()
        {
            text = new StringBuilder();
        }

        public void BeginHTML()
        {
            text.Append("<html>");
        }

        public void EndHTML()
        {
            text.Append("</html>");
        }

        public void Title(String str)
        {
            text.Append("<head><title>");
            text.Append(str);
            text.Append("</title></head>");
        }

        public void BeginPara()
        {
            text.Append("<p>");
        }

        public void EndPara()
        {
            text.Append("</p>");
        }

        public void Bold(String str)
        {
            text.Append("<b>");
            text.Append(str);
            text.Append("</b>");
        }

        public void Para(String str)
        {
            text.Append("<p>");
            text.Append(str);
            text.Append("</p>");
        }

        public void Clear()
        {
            text.Length = 0;
        }

        public override String ToString()
        {
            return text.ToString();
        }

        public void BeginBody()
        {
            text.Append("<body>");
        }

        public void EndBody()
        {
            text.Append("</body>");
        }

        public void H1(String title)
        {
            text.Append("<h1>");
            text.Append(title);
            text.Append("</h1>");
        }

        public void BeginTable()
        {
            text.Append("<table border=\"1\">");
        }

        public void EndTable()
        {
            text.Append("</table>");
        }

        public void BeginRow()
        {
            text.Append("<tr>");
        }

        public void EndRow()
        {
            text.Append("</tr>");
        }

        public void Header(String head)
        {
            text.Append("<th>");
            text.Append(head);
            text.Append("</th>");
        }

        public void Cell(String head)
        {
            Cell(head, 0);
        }

        public void Cell(String head, int colSpan)
        {
            text.Append("<td");
            if (colSpan > 0)
            {
                text.Append(" colspan=\"");
                text.Append(colSpan);
                text.Append("\"");
            }
            text.Append(">");
            text.Append(head);
            text.Append("</td>");
        }

        public void TablePair(String name, String value_ren)
        {
            BeginRow();
            Cell("<b>" + name + "</b>");
            Cell(value_ren);
            EndRow();
        }

        public void H2(String title)
        {
            text.Append("<h2>");
            text.Append(title);
            text.Append("</h2>");
        }

        public void H3(String title)
        {
            text.Append("<h3>");
            text.Append(title);
            text.Append("</h3>");
        }

        public void BeginList()
        {
            text.Append("<ul>");
        }

        public void ListItem(String str)
        {
            text.Append("<li>");
            text.Append(str);
        }

        public void EndList()
        {
            text.Append("</ul>");
        }

        public void BeginTableInCell(int colSpan)
        {
            text.Append("<td");
            if (colSpan > 0)
            {
                text.Append(" colspan=\"");
                text.Append(colSpan);
                text.Append("\"");
            }
            text.Append(">");
            text.Append("<table border=\"1\" width=\"100%\">");
        }

        public void EndTableInCell()
        {
            text.Append("</table></td>");
        }
    }
}