/*
 * Encog(tm) Core v3.0 - Java Version
 * http://www.heatonresearch.com/encog/
 * http://code.google.com/p/encog-java/
 
 * Copyright 2008-2011 Heaton Research, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *   
 * For more information on Heaton Research copyrights, licenses 
 * and trademarks visit:
 * http://www.heatonresearch.com/copyright
 */
// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 5/5/11 3:32 PM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;
using System.Text;

namespace Encog.App.Analyst.Script.Segregate
{
    /// <summary>
    /// This class specifies a target for the segregation process.
    /// </summary>
    ///
    public class AnalystSegregateTarget
    {
        /// <summary>
        /// The file target.
        /// </summary>
        ///
        private String file;

        /// <summary>
        /// Construct the segregation target.
        /// </summary>
        ///
        /// <param name="theFile">The file.</param>
        /// <param name="thePercent">The percent.</param>
        public AnalystSegregateTarget(String theFile, int thePercent)
        {
            file = theFile;
            Percent = thePercent;
        }


        /// <value>the file to set</value>
        public String File
        {
            /// <returns>the file</returns>
            get { return file; }
            /// <param name="theFile">the file to set</param>
            set { file = value; }
        }


        /// <value>the percent to set</value>
        public int Percent { /// <returns>the percent</returns>
            get; /// <param name="thePercent">the percent to set</param>
            set; }


        /// <summary>
        /// 
        /// </summary>
        ///
        public override sealed String ToString()
        {
            var result = new StringBuilder("[");
            result.Append(GetType().Name);
            result.Append(" file=");
            result.Append(file);
            result.Append(", percent=");
            result.Append(file);
            result.Append("]");
            return result.ToString();
        }
    }
}