using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Encog.Normalize.Output
{
    /// <summary>
    /// An output field, this represents the actual output from the 
    /// normalization.  Output from the normalization class is usually
    /// input to a neural network.
    ///
    /// An output field may contain several subfields that will be
    /// generated.  Call getSubfieldCount to determine how many fields
    /// will be generated.  A simple field will return 1, indicating that 
    /// this is a single field.
    /// </summary>
    public interface IOutputField
    {
        /// <summary>
        /// Calculate the value for this field.  Specify subfield of zero
        /// if this is a simple field.
        /// </summary>
        /// <param name="subfield"> The subfield index.</param>
        /// <returns>The calculated value for this field.</returns>
        double Calculate(int subfield);

        /// <summary>
        /// The numebr of fields that will actually be generated by 
        /// this field. For a simple field, this value is 1.
        /// </summary>
        int SubfieldCount { get; }

        /// <summary>
        /// Is this field part of the ideal data uses to train the
        /// neural network.
        /// </summary>
        bool Ideal { get; set; }

        /// <summary>
        /// Init this field for a new row.
        /// </summary>
        void RowInit();
    }
}
