/*
 * Encog(tm) Core v3.0 - Java Version
 * http://www.heatonresearch.com/encog/
 * http://code.google.com/p/encog-java/
 
 * Copyright 2008-2011 Heaton Research, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *   
 * For more information on Heaton Research copyrights, licenses 
 * and trademarks visit:
 * http://www.heatonresearch.com/copyright
 */
// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 5/5/11 3:33 PM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;
using System.Text;

namespace Encog.Util.Arrayutil
{
    /// <summary>
    /// A class item.
    /// </summary>
    ///
    public class ClassItem
    {
        /// <summary>
        /// The index of the class.
        /// </summary>
        ///
        private int index;

        /// <summary>
        /// The name of the class.
        /// </summary>
        ///
        private String name;

        /// <summary>
        /// Construct the object.
        /// </summary>
        ///
        /// <param name="theName">The name of the class.</param>
        /// <param name="theIndex">The index of the class.</param>
        public ClassItem(String theName, int theIndex)
        {
            name = theName;
            index = theIndex;
        }

        /// <summary>
        /// Set the index of the class.
        /// </summary>
        ///
        /// <value>The index of the class.</value>
        public int Index
        {
            /// <returns>The index of the class.</returns>
            get { return index; }
            /// <summary>
            /// Set the index of the class.
            /// </summary>
            ///
            /// <param name="theIndex">The index of the class.</param>
            set { index = value; }
        }


        /// <summary>
        /// Set the name of the class.
        /// </summary>
        ///
        /// <value>The name of the class.</value>
        public String Name
        {
            /// <returns>The name of the class.</returns>
            get { return name; }
            /// <summary>
            /// Set the name of the class.
            /// </summary>
            ///
            /// <param name="theName">The name of the class.</param>
            set { name = value; }
        }


        /// <summary>
        /// 
        /// </summary>
        ///
        public override sealed String ToString()
        {
            var result = new StringBuilder("[");
            result.Append(GetType().Name);
            result.Append(" name=");
            result.Append(name);
            result.Append(", index=");
            result.Append(index);

            result.Append("]");
            return result.ToString();
        }
    }
}